sistema_gerenciamento_funcionarios/config/routes.rb
Rails.application.routes.draw do
  #devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # root "home#index"
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  #devise_for :users, controllers: { registrations: 'users/registrations' }
  devise_for :users  
  resources :users_admin, :controller => 'users'
  
  devise_scope :user do
    root to: "devise/sessions#new"
  end
 

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
  # root "funcionarios#index"
  resources :funcionarios
  resources :departamentos
  resources :cargos
  resources :users, only: [:index, :new, :create]


  resources :admin_users, controller: 'users', only: [:index, :new, :create]

  get 'selection', to: 'pages#selection'

  get "/funcionarios", to: "funcionarios#index"
  get "/funcionarios/:id", to: "funcionarios#show"

  get "/cargos", to: "cargos#index"
  get "/departamentos", to: "departamentos#index"
end

sistema_gerenciamento_funcionarios/app/models/departamento.rb
class Departamento < ApplicationRecord
    has_many :cargos
    enum status: { ativo: 0, inativo: 1 }
end

sistema_gerenciamento_funcionarios/app/controllers/departamentos_controller.rb
class DepartamentosController < ApplicationController
  before_action :set_departamento, only: %i[show edit update destroy]
  before_action :authorize_departamento

  def index
    if current_user.admin?
      # Admin vê todos os departamentos
      if params[:nome].present?
        @departamentos = Departamento.where('nome LIKE ?', "%#{params[:nome]}%")
      else
        @departamentos = Departamento.all
      end
    elsif current_user.gestor_rh?
      # Gestor de RH vê apenas os departamentos associados
      if params[:nome].present?
        @departamentos = current_user.departamentos.where('nome LIKE ?', "%#{params[:nome]}%")
      else
        @departamentos = current_user.departamentos
      end
    end
  end

  def show
    @departamento = Departamento.find(params[:id])
    authorize @departamento
  end

  def new
    @departamento = Departamento.new
  end

  def create
    @departamento = Departamento.new(departamento_params)
    if @departamento.save
      redirect_to @departamento, notice: 'Departamento criado com sucesso.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @departamento.update(departamento_params)
      redirect_to @departamento, notice: 'Departamento atualizado com sucesso.'
    else
      render :edit
    end
  end

  def destroy
    @departamento = Departamento.find(params[:id])
    @departamento.destroy
    redirect_to departamentos_url, notice: 'Departamento excluído com sucesso.'
  end
  

  private

  def authorize_departamento
   # authorize @departamento  # Autoriza a instância, não a classe
  #  @departamento = Departamento.new  # Cria uma nova instância de Departamento
  end
  

  def set_departamento
    @departamento = Departamento.find(params[:id])
  end

  def departamento_params
    params.require(:departamento).permit(:nome, :descricao, :codigo, :localizacao, :status)
  end
end

sistema_gerenciamento_funcionarios/app/helpers/departamentos_helper.rb
module DepartamentosHelper
end

sistema_gerenciamento_funcionarios/app/views/departamentos/edit.html.erb
<h1>Editar Departamento</h1>
<%= form_with(model: @departamento, local: true) do |form| %>
  <div>
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>
  <div>
    <%= form.label :descricao %>
    <%= form.text_area :descricao %>
  </div>
  <div>
    <%= form.label :codigo %>
    <%= form.text_field :codigo %>
  </div>
  <div>
    <%= form.label :localizacao %>
    <%= form.text_field :localizacao %>
  </div>
  <div>
    <%= form.label :status %>
    <%= form.select :status, Departamento.statuses.keys.map { |s| [s.humanize, s] } %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>
<%= link_to 'Voltar', departamento_path(@departamento) %>

sistema_gerenciamento_funcionarios/app/views/departamentos/index.html.erb
<h1>Departamentos</h1>

<%= form_with url: departamentos_path, method: :get, local: true do %>
  <div class="field">
    <%= label_tag :nome, 'Nome do Departamento' %>
    <%= text_field_tag :nome, params[:nome] %>
  </div>
  <div class="actions">
    <%= submit_tag 'Buscar' %>
  </div>
<% end %>

<div class="centralizado">
  <% if policy(Departamento).create? %> <!-- Apenas admin pode ver o botão de novo departamento -->
    <%= link_to 'Novo Departamento', new_departamento_path %>
  <% end %>

  <%= link_to 'Menu', selection_path, class: "btn btn-primary" %>
</div>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Código</th>
      <th>Localização</th>
      <th>Status</th>
      <th>Ações</th>
    </tr>
  </thead>
  <tbody>
    <% @departamentos.each do |departamento| %>
      <% if policy(departamento).show? %> 
        <tr>
          <td><%= departamento.nome %></td>
          <td><%= departamento.codigo %></td>
          <td><%= departamento.localizacao %></td>
          <td><%= departamento.status %></td>
          <td>
            <%= link_to 'Mostrar', departamento if policy(departamento).show? %> 
            <% if policy(departamento).update? %>
              | <%= link_to 'Editar', edit_departamento_path(departamento) %>
            <% end %>
            <% if policy(departamento).destroy? %>
              | <%= link_to 'Excluir', departamento, method: :delete, data: { confirm: 'Tem certeza?' } %>
            <% end %>
          </td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

sistema_gerenciamento_funcionarios/app/views/departamentos/new.html.erb
<h1>Novo Departamento</h1>
<%= form_with(model: @departamento, local: true) do |form| %>
  <div>
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>
  <div>
    <%= form.label :descricao %>
    <%= form.text_area :descricao %>
  </div>
  <div>
    <%= form.label :codigo %>
    <%= form.text_field :codigo %>
  </div>
  <div>
    <%= form.label :localizacao %>
    <%= form.text_field :localizacao %>
  </div>
  <div>
    <%= form.label :status %>
    <%= form.select :status, Departamento.statuses.keys.map { |s| [s.humanize, s] } %>
  </div>
  <div>
  <%= form.submit 'Salvar Departamento' %>
</div>
<% end %>
<%= link_to 'Voltar', departamentos_path %>

sistema_gerenciamento_funcionarios/app/views/departamentos/show.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Departamento</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      background-color: #f8f9fa;
      margin: 0;
      padding: 0;
    }
    .container {
      width: 80%;
      margin: auto;
      padding: 20px;
    }
    .card {
      background: white;
      border-radius: 8px;
      box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
      padding: 20px;
      margin-top: 20px;
    }
    .card h1 {
      margin-top: 0;
      font-size: 2rem;
      color: #343a40;
    }
    .card p {
      font-size: 1rem;
      margin: 10px 0;
      color: #495057;
    }
    .card strong {
      color: #212529;
    }
    .button-container {
      margin-top: 20px;
    }
    .button-container a {
      text-decoration: none;
      color: white;
      background-color: #007bff;
      padding: 10px 20px;
      border-radius: 5px;
      font-size: 1rem;
    }
    .button-container a:hover {
      background-color: #0056b3;
    }
  </style>
</head>
<body>
  <div class="container">
    <div class="card">
      <h1><%= @departamento.nome %></h1>
      <p>
        <strong>Descrição:</strong>
        <br>
        <%= @departamento.descricao %>
      </p>
      <p>
        <strong>Código:</strong>
        <br>
        <%= @departamento.codigo %>
      </p>
      <p>
        <strong>Localização:</strong>
        <br>
        <%= @departamento.localizacao %>
      </p>
      <p>
        <strong>Status:</strong>
        <br>
        <%= @departamento.status %>
      </p>
      <div class="button-container">
        <%= link_to 'Voltar', departamentos_path, class: 'btn' %>
      </div>
    </div>
  </div>
</body>
</html>