sistema_gerenciamento_funcionarios/config/routes.rb
Rails.application.routes.draw do
  #devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # root "home#index"
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  #devise_for :users, controllers: { registrations: 'users/registrations' }
  devise_for :users  
  resources :users_admin, :controller => 'users'
  
  devise_scope :user do
    root to: "devise/sessions#new"
  end
 

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
  # root "funcionarios#index"
  resources :funcionarios
  resources :departamentos
  resources :cargos
  resources :users, only: [:index, :new, :create]


  resources :admin_users, controller: 'users', only: [:index, :new, :create]

  get 'selection', to: 'pages#selection'

  get "/funcionarios", to: "funcionarios#index"
  get "/funcionarios/:id", to: "funcionarios#show"

  get "/cargos", to: "cargos#index"
  get "/departamentos", to: "departamentos#index"
end

sistema_gerenciamento_funcionarios/app/views/pages/selection.html.erb
<!-- app/views/pages/selection.html.erb -->

<% if user_signed_in? %>
  <div class="user-info-container">
    <div class="user-info-left">
      <strong class="user-email"><%= current_user.email %></strong>
      <div class="user-details">
        <span class="user-name"><%= current_user.nome %></span>
        <span class="user-role"><%= current_user.role.humanize %></span>
      </div>
    </div>
    <div class="user-info-right">
      <%= link_to "Sair", destroy_user_session_path, method: :delete, class: "logout-link" %>
    </div>
  </div>
<% end %>



<h1 style="text-align: center;">Selecione uma Opção</h1>

<div class="card-container" style="display: flex; justify-content: center; gap: 20px; flex-wrap: wrap;">


<!-- Card para Departamentos -->
  <div class="card" style="border: 1px solid #ddd; padding: 20px; text-align: center; width: 200px;">
    <%= link_to departamentos_path, style: "text-decoration: none;" do %>
      <%= image_tag 'departamentos.png', alt: 'Departamentos', style: 'width: 100%; height: auto;' %>
      <h2>Departamentos</h2>
    <% end %>
  </div>


  <!-- Card para Cargos -->
  <div class="card" style="border: 1px solid #ddd; padding: 20px; text-align: center; width: 200px;">
    <%= link_to cargos_path, style: "text-decoration: none;" do %>
      <%= image_tag 'cargos.png', alt: 'Cargos', style: 'width: 100%; height: auto;' %>
      <h2>Cargos</h2>
    <% end %>
  </div>

  <!-- Card para Funcionários -->
  <div class="card" style="border: 1px solid #ddd; padding: 20px; text-align: center; width: 200px;">
    <%= link_to funcionarios_path, style: "text-decoration: none;" do %>
      <%= image_tag 'funcionarios.png', alt: 'Funcionários', style: 'width: 100%; height: auto;' %>
      <h2>Funcionários</h2>
    <% end %>
  </div>

  <% if current_user.admin? %>
  <div class="card" style="border: 1px solid #ddd; padding: 20px; text-align: center; width: 200px;">
    <%= link_to users_path , style: "text-decoration: none;" do %> <!-- Redireciona para a lista de usuários -->
      <%= image_tag 'user.png', alt: 'Usuários', style: 'width: 100%; height: auto;' %>
      <h2>Usuários</h2>
    <% end %>
  </div>
<% end %>


</div>