sistema_gerenciamento_funcionarios/config/routes.rb
Rails.application.routes.draw do
  #devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # root "home#index"
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  #devise_for :users, controllers: { registrations: 'users/registrations' }
  devise_for :users  
  resources :users_admin, :controller => 'users'
  
  devise_scope :user do
    root to: "devise/sessions#new"
  end
 

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
  # root "funcionarios#index"
  resources :funcionarios
  resources :departamentos
  resources :cargos
  resources :users, only: [:index, :new, :create]


  resources :admin_users, controller: 'users', only: [:index, :new, :create]

  get 'selection', to: 'pages#selection'

  get "/funcionarios", to: "funcionarios#index"
  get "/funcionarios/:id", to: "funcionarios#show"

  get "/cargos", to: "cargos#index"
  get "/departamentos", to: "departamentos#index"
end

sistema_gerenciamento_funcionarios/app/models/cargo.rb
class Cargo < ApplicationRecord
  belongs_to :departamento

  enum nivel: { junior: 0, pleno: 1, senior: 2, nao_se_aplica: 3 }
  enum status: { ativo: 0, inativo: 1 }
  validates :nivel, presence: true

end

sistema_gerenciamento_funcionarios/app/controllers/cargos_controller.rb
class CargosController < ApplicationController
  before_action :set_cargo, only: %i[show edit update destroy]

  def index
    if current_user.admin?
      # Admin vê todos os cargos
      if params[:nome].present?
        @cargos = Cargo.where('nome LIKE ?', "%#{params[:nome]}%")
      else
        @cargos = Cargo.all
      end
    elsif current_user.gestor_rh?
      # Gestor de RH vê apenas os cargos de seu departamento
      if params[:nome].present?
        @cargos = Cargo.joins(:departamento).where(departamento: { id: current_user.departamentos.ids }).where('cargos.nome LIKE ?', "%#{params[:nome]}%")
      else
        @cargos = Cargo.joins(:departamento).where(departamento: { id: current_user.departamentos.ids })
      end
    end
  end

  def show
  end

  def new
    @cargo = Cargo.new
    # Verifica se o usuário é admin para exibir todos os departamentos
    @departamentos = current_user.admin? ? Departamento.all : current_user.departamentos_permitidos
  end

  def create
    @cargo = Cargo.new(cargo_params)

    # Verifica se o usuário pode criar cargos para o departamento escolhido
    if current_user.admin? || current_user.departamentos_permitidos.include?(@cargo.departamento)
      if @cargo.save
        redirect_to @cargo, notice: 'Cargo criado com sucesso.'
      else
        render :new
      end
    else
      flash[:alert] = "Você não tem permissão para criar cargos para este departamento."
      render :new
    end
  end

  def edit
  end

  def update
    if @cargo.update(cargo_params)
      redirect_to @cargo, notice: 'Cargo atualizado com sucesso.'
    else
      render :edit
    end
  end

  def destroy
    @cargo.destroy
    redirect_to cargos_url, notice: 'Cargo excluído com sucesso.'
  end

  private

  def set_cargo
    @cargo = Cargo.find(params[:id])
  end

  def cargo_params
    params.require(:cargo).permit(:nome, :descricao, :departamento_id, :nivel, :salario_base, :requisitos, :beneficios, :status)
  end
  
end

sistema_gerenciamento_funcionarios/app/helpers/cargos_helper.rb
module CargosHelper
end

sistema_gerenciamento_funcionarios/app/views/cargos/edit.html.erb
<h1>Editar Cargo</h1>

<%= form_with(model: @cargo, local: true) do |form| %>
  <div>
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>
  
  <div>
    <%= form.label :descricao %>
    <%= form.text_area :descricao %>
  </div>

  <div>
    <%= form.label :departamento_id, "Departamento" %>
    <%= form.collection_select :departamento_id, Departamento.all, :id, :nome, prompt: "Selecione um departamento" %>
  </div>

  <div>
  <%= form.label :nivel %>
  <%= form.select :nivel, Cargo.nivels.keys.map { |s| [s.humanize, s] }, prompt: "Selecione um nível" %>
</div>


  <div>
    <%= form.label :salario_base %>
    <%= form.number_field :salario_base, step: '0.01' %>
  </div>

  <div>
    <%= form.label :requisitos %>
    <%= form.text_area :requisitos %>
  </div>

  <div>
    <%= form.label :beneficios %>
    <%= form.text_area :beneficios %>
  </div>

  <div>
    <%= form.label :status %>
    <%= form.select :status, Cargo.statuses.keys.map { |s| [s.humanize, s] } %>
  </div>

  <div>
  <%= form.submit %>
</div>
<% end %>
<%= link_to 'Voltar', cargo_path(@cargo) %>

sistema_gerenciamento_funcionarios/app/views/cargos/index.html.erb
<h1>Cargos</h1>

<%= form_with url: cargos_path, method: :get, local: true do %>
  <div class="field">
    <%= label_tag :nome, 'Nome do Cargo' %>
    <%= text_field_tag :nome, params[:nome] %>
  </div>
  <div class="actions">
    <%= submit_tag 'Buscar' %>
  </div>
<% end %>

<div class="centralizado">
  <%= link_to 'Novo Cargo', new_cargo_path %>
  <%= link_to 'Menu', selection_path, class: "btn btn-primary" %>
</div>


<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Departamento</th>
      <th>Nível</th>
      <th>Salário Base</th>
      <th>Status</th>
      <th>Ações</th>
    </tr>
  </thead>
  <tbody>
    <% @cargos.each do |cargo| %>
      <% if policy(cargo).show? %>
        <tr>
          <td><%= cargo.nome %></td>
          <td><%= cargo.departamento.nome %></td>
          <td><%= cargo.nivel %></td>
          <td><%= number_to_currency(cargo.salario_base) %></td>
          <td><%= cargo.status.humanize %></td>
          <td>
            <%= link_to 'Mostrar', cargo if policy(cargo).show? %> |
            <%= link_to 'Editar', edit_cargo_path(cargo) if policy(cargo).update? %> |
            <%= link_to 'Excluir', cargo, method: :delete, data: { confirm: 'Tem certeza?' } %>
            </td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

sistema_gerenciamento_funcionarios/app/views/cargos/new.html.erb
<h1>Novo Cargo</h1>

<%= form_with(model: @cargo, local: true) do |form| %>
  <div>
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>
  
  <div>
    <%= form.label :descricao %>
    <%= form.text_area :descricao %>
  </div>

  <div>
  <%= form.label :departamento_id, "Departamento" %>
  <%= form.collection_select :departamento_id, @departamentos, :id, :nome, prompt: "Selecione um departamento" %>
</div>

  
  <div>
  <%= form.label :nivel %>
  <%= form.select :nivel, Cargo.nivels.keys.map { |s| [s.humanize, s] }, prompt: "Selecione um nível" %>
</div>


  <div>
    <%= form.label :salario_base %>
    <%= form.number_field :salario_base, step: '0.01' %>
  </div>

  <div>
    <%= form.label :requisitos %>
    <%= form.text_area :requisitos %>
  </div>

  <div>
    <%= form.label :beneficios %>
    <%= form.text_area :beneficios %>
  </div>

  <div>
    <%= form.label :status %>
    <%= form.select :status, Cargo.statuses.keys.map { |s| [s.humanize, s] } %>
  </div>

  <div>
    <%= form.submit 'Salvar Cargo' %>
  </div>
<% end %>

<%= link_to 'Voltar', cargos_path %>

sistema_gerenciamento_funcionarios/app/views/cargos/show.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Detalhes do Cargo</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      background-color: #f8f9fa;
      margin: 0;
      padding: 0;
    }
    .container {
      width: 80%;
      margin: auto;
      padding: 20px;
    }
    .card {
      background: white;
      border-radius: 8px;
      box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
      padding: 20px;
      margin-top: 20px;
    }
    .card h1 {
      margin-top: 0;
      font-size: 2rem;
      color: #343a40;
    }
    .card p {
      font-size: 1rem;
      margin: 10px 0;
      color: #495057;
    }
    .card strong {
      color: #212529;
    }
    .button-container {
      margin-top: 20px;
    }
    .button-container a {
      text-decoration: none;
      color: white;
      background-color: #007bff;
      padding: 10px 20px;
      border-radius: 5px;
      font-size: 1rem;
    }
    .button-container a:hover {
      background-color: #0056b3;
    }
  </style>
</head>
<body>
  <div class="container">
    <div class="card">
      <h1><%= @cargo.nome %></h1>
      <p>
        <strong>Descrição:</strong>
        <br>
        <%= @cargo.descricao %>
      </p>
      <p>
        <strong>Departamento:</strong>
        <br>
        <%= @cargo.departamento.nome %>
      </p>
      <p>
        <strong>Nível:</strong>
        <br>
        <%= @cargo.nivel %>
      </p>
      <p>
        <strong>Salário Base:</strong>
        <br>
        <%= number_to_currency(@cargo.salario_base) %>
      </p>
      <p>
        <strong>Requisitos:</strong>
        <br>
        <%= @cargo.requisitos %>
      </p>
      <p>
        <strong>Benefícios:</strong>
        <br>
        <%= @cargo.beneficios %>
      </p>
      <p>
        <strong>Status:</strong>
        <br>
        <%= @cargo.status.humanize %>
      </p>
      <div class="button-container">
        <%= link_to 'Voltar', cargos_path, class: 'btn' %>
      </div>
    </div>
  </div>
</body>
</html>