sistema_gerenciamento_funcionarios/config/routes.rb
Rails.application.routes.draw do
  #devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # root "home#index"
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  #devise_for :users, controllers: { registrations: 'users/registrations' }
  devise_for :users  
  resources :users_admin, :controller => 'users'
  
  devise_scope :user do
    root to: "devise/sessions#new"
  end
 

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
  # root "funcionarios#index"
  resources :funcionarios
  resources :departamentos
  resources :cargos
  resources :users, only: [:index, :new, :create]


  resources :admin_users, controller: 'users', only: [:index, :new, :create]

  get 'selection', to: 'pages#selection'

  get "/funcionarios", to: "funcionarios#index"
  get "/funcionarios/:id", to: "funcionarios#show"

  get "/cargos", to: "cargos#index"
  get "/departamentos", to: "departamentos#index"
end

sistema_gerenciamento_funcionarios/app/models/funcionario.rb
class Funcionario < ApplicationRecord
  has_many :enderecos, dependent: :destroy
  accepts_nested_attributes_for :enderecos, allow_destroy: true
  belongs_to :cargo
  has_one :departamento, through: :cargo  
  validates :nome_completo, :cpf, :email, :data_nascimento, :data_contratacao, presence: true
  validates :cpf, uniqueness: true
  validates :email, uniqueness: true
  validates :salario, numericality: { greater_than_or_equal_to: 0 }
  
  enum status: { ativo: 'Ativo', inativo: 'Inativo', em_licenca: 'Em licença' }
end

sistema_gerenciamento_funcionarios/app/controllers/funcionarios_controller.rb
class FuncionariosController < ApplicationController
  before_action :set_funcionario, only: %i[show edit update destroy]
  before_action :set_departamentos_e_cargos, only: %i[new create edit update]


  # GET /funcionarios
  def index
    # Obter todos os funcionários
    @funcionarios = Funcionario.all

    # Obter os departamentos associados ao usuário logado
    if current_user.admin?
      @departamentos = Departamento.all
    else
      @departamentos = current_user.departamentos
    end

    # Filtro por nome do funcionário
    @funcionarios = @funcionarios.where('nome_completo LIKE ?', "%#{params[:nome]}%") if params[:nome].present?

    # Filtro por departamento, apenas os departamentos aos quais o usuário tem acesso
    if params[:departamento_id].present?
      departamento_id = params[:departamento_id].to_i
      @funcionarios = @funcionarios.joins(cargo: :departamento).where('departamentos.id = ?', departamento_id)
    else
      # Mostrar funcionários apenas dos departamentos associados ao usuário
      @funcionarios = @funcionarios.joins(cargo: :departamento).where(departamentos: { id: @departamentos.pluck(:id) })
    end

    # Filtro por data de contratação
    if params[:data_contratacao_inicio].present? && params[:data_contratacao_fim].present?
      @funcionarios = @funcionarios.where('data_contratacao BETWEEN ? AND ?', params[:data_contratacao_inicio], params[:data_contratacao_fim])
    elsif params[:data_contratacao_inicio].present?
      @funcionarios = @funcionarios.where('data_contratacao >= ?', params[:data_contratacao_inicio])
    elsif params[:data_contratacao_fim].present?
      @funcionarios = @funcionarios.where('data_contratacao <= ?', params[:data_contratacao_fim])
    end
  end

  # GET /funcionarios/1
  def show
  end

  # GET /funcionarios/new
  def new
    @funcionario = Funcionario.new
    @funcionario.enderecos.build # Adiciona um endereço vazio para o formulário
  end

  # POST /funcionarios
  def create
    @funcionario = Funcionario.new(funcionario_params)
    if @funcionario.save
      redirect_to @funcionario, notice: 'Funcionário criado com sucesso.'
    else
      render :new
    end
  end

  # GET /funcionarios/1/edit
  def edit
  end

  # PATCH/PUT /funcionarios/1
  def update
    if @funcionario.update(funcionario_params)
      redirect_to @funcionario, notice: 'Funcionário atualizado com sucesso.'
    else
      render :edit
    end
  end

  # DELETE /funcionarios/1
  def destroy
    @funcionario.destroy
    redirect_to funcionarios_url, notice: 'Funcionário excluído com sucesso.'
  end

  private

  def set_departamentos_e_cargos
    if current_user.admin?
      @departamentos = Departamento.all
      @cargos = Cargo.all
    else
      # Filtra departamentos e cargos de acordo com o usuário
      @departamentos = current_user.departamentos
      @cargos = Cargo.where(departamento_id: @departamentos.pluck(:id))
    end
  end

  # Define o funcionário com base no id
  def set_funcionario
    @funcionario = Funcionario.find(params[:id])
  end

  # Permite parâmetros confiáveis
  def funcionario_params
    params.require(:funcionario).permit(
      :nome_completo, :cpf, :email, :data_nascimento, :data_contratacao, :salario, :status, :cargo_id,
      :genero, :rg, :telefone, 
      enderecos_attributes: [:id, :rua, :numero, :bairro, :cidade, :estado, :cep, :_destroy]
    )
  end
end

sistema_gerenciamento_funcionarios/app/helpers/funcionarios_helper.rb
module FuncionariosHelper
end

sistema_gerenciamento_funcionarios/app/views/funcionarios/edit.html.erb
<h1>Editar Funcionário</h1>

<%= form_with(model: @funcionario, local: true) do |form| %>
  <div class="form-group">
    <%= form.label :nome_completo %>
    <%= form.text_field :nome_completo, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :data_nascimento %>
    <%= form.date_field :data_nascimento, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :genero %>
    <%= form.select :genero, options_for_select([['Masculino', 'Masculino'], ['Feminino', 'Feminino'], ['Outro', 'Outro']], @funcionario.genero), { prompt: 'Selecione o Gênero' }, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :cpf %>
    <%= form.text_field :cpf, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :rg %>
    <%= form.text_field :rg, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :telefone %>
    <%= form.text_field :telefone, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :email %>
    <%= form.email_field :email, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :cargo_id %>
    <%= form.collection_select :cargo_id, Cargo.all, :id, :nome, prompt: 'Selecione um Cargo', class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :data_contratacao %>
    <%= form.date_field :data_contratacao, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :salario %>
    <%= form.number_field :salario, step: '0.01', class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :status %>
    <%= form.select :status, Funcionario.statuses.keys.map { |status| [status.humanize, status] }, {}, class: 'form-control' %>
  </div>

  <h3>Endereços</h3>

  <div id="enderecos">
    <%= form.fields_for :enderecos do |endereco_form| %>
      <div class="form-group">
        <%= endereco_form.label :rua %>
        <%= endereco_form.text_field :rua, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= endereco_form.label :numero %>
        <%= endereco_form.text_field :numero, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= endereco_form.label :bairro %>
        <%= endereco_form.text_field :bairro, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= endereco_form.label :cidade %>
        <%= endereco_form.text_field :cidade, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= endereco_form.label :estado %>
        <%= endereco_form.text_field :estado, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= endereco_form.label :cep %>
        <%= endereco_form.text_field :cep, class: 'form-control' %>
      </div>

      <%= link_to 'Remover Endereço', '#', class: 'remove_fields', data: {id: endereco_form.object.id} %>
    <% end %>
  </div>

  <%= form.submit 'Atualizar Funcionário', class: 'btn btn-primary' %>
<% end %>

<%= link_to 'Voltar', funcionario_path(@funcionario), class: 'btn btn-secondary' %>

sistema_gerenciamento_funcionarios/app/views/funcionarios/index.html.erb
<h1>Funcionários</h1>

<%= form_with url: funcionarios_path, method: :get, local: true do %>
  <div class="field">
    <%= label_tag :nome, 'Nome do Funcionário' %>
    <%= text_field_tag :nome, params[:nome] %>
  </div>
  
  <div class="field">
    <%= label_tag :departamento_id, 'Departamento' %>
    <%= select_tag :departamento_id, options_from_collection_for_select(@departamentos, :id, :nome, params[:departamento_id]), include_blank: 'Todos' %>
  </div>
  
  <div class="field">
    <%= label_tag :data_contratacao_inicio, 'Data de Contratação Início' %>
    <%= date_field_tag :data_contratacao_inicio, params[:data_contratacao_inicio] %>
  </div>
  
  <div class="field">
    <%= label_tag :data_contratacao_fim, 'Data de Contratação Fim' %>
    <%= date_field_tag :data_contratacao_fim, params[:data_contratacao_fim] %>
  </div>

  <div class="actions">
    <%= submit_tag 'Buscar' %>
  </div>
<% end %>


<div class="centralizado">
  <%= link_to 'Novo Funcionário', new_funcionario_path %>
  <%= link_to 'Menu', selection_path, class: "btn btn-primary" %>
</div>


<table class="table">
  <thead>
    <tr>
      <th>Nome Completo</th>
      <th>Data de Nascimento</th>
      <th>CPF</th>
      <th>Telefone</th>
      <th>Cargo</th>
      <th>Status</th>
      <th>Ações</th>
    </tr>
  </thead>

  <tbody>
  <% if @funcionarios.present? %>

    <% @funcionarios.each do |funcionario| %>
      <tr>
        <td><%= funcionario.nome_completo %></td>
        <td><%= funcionario.data_nascimento %></td>
        <td><%= funcionario.cpf %></td>
        <td><%= funcionario.telefone %></td>
        <td><%= funcionario.cargo.nome %></td>
        <td><%= funcionario.status %></td>
        <td>
          <%= link_to 'Mostrar', funcionario_path(funcionario), class: 'btn btn-info' %>
          <%= link_to 'Editar', edit_funcionario_path(funcionario), class: 'btn btn-warning' %>
          <%= link_to 'Excluir', funcionario_path(funcionario), method: :delete, data: { confirm: 'Tem certeza?' }, class: 'btn btn-danger' %>
        </td>
      </tr>
    <% end %>
    <% else %>
  <tr>
    <td colspan="X">Nenhum funcionário encontrado</td> <!-- X sendo o número de colunas -->
  </tr>
<% end %>
  </tbody>
</table>

sistema_gerenciamento_funcionarios/app/views/funcionarios/new.html.erb
<h1>Criar Novo Funcionário</h1>

<%= form_with(model: @funcionario, local: true) do |form| %>
  <div class="form-group">
    <%= form.label :nome_completo %>
    <%= form.text_field :nome_completo, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :data_nascimento %>
    <%= form.date_field :data_nascimento, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :genero %>
    <%= form.select :genero, options_for_select([['Masculino', 'Masculino'], ['Feminino', 'Feminino'], ['Outro', 'Outro']], @funcionario.genero), { prompt: 'Selecione o Gênero' }, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= form.label :cpf %>
    <%= form.text_field :cpf, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :rg %>
    <%= form.text_field :rg, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :telefone %>
    <%= form.text_field :telefone, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :email %>
    <%= form.email_field :email, class: 'form-control' %>
  </div>


  <div class="field">
    <%= form.label :cargo_id, 'Cargo' %>
    <%= form.select :cargo_id, options_from_collection_for_select(@cargos, :id, :nome, @funcionario.cargo_id), { prompt: 'Selecione o Cargo' } %>
  </div>

  <div class="form-group">
    <%= form.label :data_contratacao %>
    <%= form.date_field :data_contratacao, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :salario %>
    <%= form.number_field :salario, step: '0.01', class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :status %>
    <%= form.select :status, Funcionario.statuses.keys.map { |status| [status.humanize, status] }, {}, class: 'form-control' %>
  </div>

  <h3>Endereços</h3>

  <div id="enderecos">
    <%= form.fields_for :enderecos do |endereco_form| %>
      <div class="form-group">
        <%= endereco_form.label :rua %>
        <%= endereco_form.text_field :rua, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= endereco_form.label :numero %>
        <%= endereco_form.text_field :numero, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= endereco_form.label :bairro %>
        <%= endereco_form.text_field :bairro, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= endereco_form.label :cidade %>
        <%= endereco_form.text_field :cidade, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= endereco_form.label :estado %>
        <%= endereco_form.text_field :estado, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= endereco_form.label :cep %>
        <%= endereco_form.text_field :cep, class: 'form-control' %>
      </div>

    <% end %>
  </div>

  <div>
  <%= form.submit 'Salvar Funcionário' %>
</div>
<% end %>
<%= link_to 'Voltar', funcionarios_path, class: 'btn btn-secondary' %>

sistema_gerenciamento_funcionarios/app/views/funcionarios/show.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Detalhes do Funcionário</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      background-color: #f8f9fa;
      margin: 0;
      padding: 0;
    }
    .container {
      width: 80%;
      margin: auto;
      padding: 20px;
    }
    .card {
      background: white;
      border-radius: 8px;
      box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
      padding: 20px;
      margin-top: 20px;
    }
    .card h1 {
      margin-top: 0;
      font-size: 2rem;
      color: #343a40;
    }
    .card p, .card ul {
      font-size: 1rem;
      margin: 10px 0;
      color: #495057;
    }
    .card strong {
      color: #212529;
    }
    .address-list {
      list-style-type: none;
      padding: 0;
      margin: 0;
    }
    .address-list li {
      background: #e9ecef;
      border-radius: 4px;
      padding: 10px;
      margin-bottom: 10px;
    }
    .button-container {
      margin-top: 20px;
    }
    .button-container a {
      text-decoration: none;
      color: white;
      background-color: #007bff;
      padding: 10px 20px;
      border-radius: 5px;
      font-size: 1rem;
    }
    .button-container a:hover {
      background-color: #0056b3;
    }
  </style>
</head>
<body>
  <div class="container">
    <div class="card">
      <h1><%= @funcionario.nome_completo %></h1>
      <p>
        <strong>CPF:</strong>
        <br>
        <%= @funcionario.cpf %>
      </p>
      <p>
        <strong>Email:</strong>
        <br>
        <%= @funcionario.email %>
      </p>
      <p>
        <strong>Data de Nascimento:</strong>
        <br>
        <%= @funcionario.data_nascimento.strftime("%d/%m/%Y") %>
      </p>
      <p>
        <strong>Data de Contratação:</strong>
        <br>
        <%= @funcionario.data_contratacao.strftime("%d/%m/%Y") %>
      </p>
      <p>
        <strong>Salário:</strong>
        <br>
        <%= number_to_currency(@funcionario.salario) %>
      </p>
      <p>
        <strong>Status:</strong>
        <br>
        <%= @funcionario.status %>
      </p>

      <% if @funcionario.enderecos.any? %>
        <h2>Endereços</h2>
        <ul class="address-list">
          <% @funcionario.enderecos.each do |endereco| %>
            <li>
              <strong>Rua:</strong> <%= endereco.rua %>, 
              <strong>Número:</strong> <%= endereco.numero %>, 
              <strong>Bairro:</strong> <%= endereco.bairro %>, 
              <strong>Cidade:</strong> <%= endereco.cidade %>, 
              <strong>Estado:</strong> <%= endereco.estado %>, 
              <strong>CEP:</strong> <%= endereco.cep %>
            </li>
          <% end %>
        </ul>
      <% end %>

      <p>
        <strong>Cargo:</strong>
        <br>
        <%= @funcionario.cargo.nome %>
      </p>

      <div class="button-container">
        <%= link_to 'Voltar', funcionarios_path, class: 'btn' %>
      </div>
    </div>
  </div>
</body>
</html>